### PR TITLE
#3 allow to customize the target for Next / Previous

### PR DESCRIPTION
**Pull request by herzbube**
To achieve the goal, an IWizard object must now be configured with an
INavigationStrategy object. WizardBase by default configures itself
with an DefaultNavigationStrategy object, which navigates sequentially
forward or backward through the currently configured wizard pages.
A concrete subclass of WizardBase can provide its own custom
implementation of INavigationStrategy to modify the default behaviour
(e.g. to skip one or more wizard pages based on the user's answers from
a previous page).

### CODE REVIEW

**Comment by herzbube** [comment]
I assumed you would expect me to assign copyright to WildGums, so I just added the default boilerplate at the top of the two new files.

**Comment by herzbube** [comment]
I noticed that navigating backwards through the wizard is not treated the same as navigating forward. Specifically in WizardBase

- MoveBackAsync does not invoke SaveAndCloseViewModelAsync()
- CanMoveBack does not invoke ValidateViewModel()

I assumed that this is the intent, so didn't change anything in that regard. But can you provide a bit of detail why this is the case?

**Comment by GeertvanHorrik** [comment]
The reason is that we want to allow users to navigate back (because it's not committing anything at that stage). When clicking back, the validation should not kick in because a user is going back anyway (that was our idea at the time). Only when moving to a next page, we want to ensure the data entered is correct.

**Comment by GeertvanHorrik** [comment]
Hi @herzbube , was this answer sufficient or is there something you want to discuss before merging this pr?

**Comment by herzbube** [comment]
Apologies, I didn't realize you were waiting for my comment. Yes, your answer was sufficient, definitively. I mainly wanted to make sure that by not modifying these "navigate backward" functions I hadn't overlooked something. Even if I were to disagree with your design decision (which I don't), this PR wouldn't be the place to discuss the issue. So, by all means, go ahead and merge.

**Comment by GeertvanHorrik** [comment]
Thanks for the pr. Released a new prerelease, 1.1.0-unstable.26.

**Pull request merged**
